### ISSUE TITLE
Can't pickle SwigPyObject objects

### ISSUE THREAD

**Issue by shivtrig** [guillermo-navas-palencia/optbinning#86]
Hi,

I am not able to pickle the BinningProcess object after fitting it.
It throws me an error saying 'can't pickle SwigPyObject objects'. 

Also, I noticed that the versions >=0.9.0 of optbinning contains a save method for the BinningProcess class. But when I try to install versions >=0.9.0, it throws me an error saying 'Failed building wheel for ecos and 'Failed building wheel for scs'. 

Can you please provide me a solution to pickle the BinningProcess object?

**Comment by guillermo-navas-palencia** [comment]
Hi @shivtrig,

The pickle error has been fixed in the latest version (0.9.1).

I am assuming you are using Windows. Version >= 0.9.0 requires RoPWR, which in turn requires CVXPY (ECOS and SCS). To install CVXPY for Windows you need to have Visual C++ compiler (build tools). See: https://visualstudio.microsoft.com/es/downloads/.

If you install version 0.9.1 all these issues should disappear. Let me know if you still encounter problems.

**Comment by shivtrig** [comment]
Hi @guillermo-navas-palencia,

Thank you for the reply! Yeah, I am using Windows 10. 

I was able to successfully install the latest version (0.9.1) using the Visual Studio Build Tools. 
But, it still throws me the same error saying 'can't pickle SwigPyObject objects' when I try to pickle the BinningProcess object?

![image](https://user-images.githubusercontent.com/53851584/109913722-7acb8000-7cd4-11eb-8d4e-efd15509a43a.png)

**Comment by guillermo-navas-palencia** [comment]
Hi @shivtrig,

I just tested the binning process and the save method in two Windows 10 machine without problems. I would suggest using a virtualenv to see whether there are problems with the python libraries within your environment.

**Comment by shivtrig** [comment]
Hi @guillermo-navas-palencia,

I am not using multi-processing. 

**Code**

```
import pandas as pd
import numpy as np
from optbinning import BinningProcess

df  = pd.read_csv('')

features = [...]

X = df[features]
y = df['target'].values

user_splits_1 = [...]
user_splits_2 = [...]

var_1 = {"solver":"mip","split_digits": 0,"min_bin_size":0.10}
var_2 = {"solver":"mip","split_digits": 0,"min_bin_size":0.10,"special_codes":[...]}
var_3 = {"solver":"mip","split_digits": 0,"min_bin_size":0.10,"special_codes":[...]}
var_4 = {"solver":"mip","split_digits": 0,"min_bin_size":0.10,"user_splits":user_splits_2}
var_5 = {"solver":"mip","user_splits":user_splits_1}
var_6 = {"solver":"mip"}

categorical_variables = ["h","i"]

binning_fit_params = {"a": var_1,"b": var_1,"c" : var_1, "d": var_1, "e": var_1,
                      "f":var_2,
                     "g":var_3,
                     "h":var_4,
                     "i":var_5,
                     "j":var_6}

binning_process = BinningProcess(features,categorical_variables=categorical_variables,binning_fit_params=binning_fit_params)

binning_process.fit(X, y)

file_path = ''
binning_process.save(file_path)
```

**Comment by guillermo-navas-palencia** [comment]
Hi @shivtrig,

The code is absolutely correct. Could you try it on a different Windows machine or another OS (Linux / Mac)? I am afraid the error is not entirely related to OptBinning.

**Comment by shivtrig** [comment]
Hi @guillermo-navas-palencia, 

Yeah, sure. Would you suggest any workaround for this issue? Meanwhile, I will try it on a different machine and let you know.

**Comment by guillermo-navas-palencia** [comment]
Any progress on this? Sorry, but I do not know any workaround.

**Comment by naenumtou** [comment]
@shivtrig I think you could try on Google Colab, it might help.

**Comment by shivtrig** [comment]
Hi @guillermo-navas-palencia, 

Not yet. I will try it on a different Windows machine and check.

**Comment by shivtrig** [comment]
@naenumtou Thank you for the suggestion!  But, I have already tried it on Google Colab too. It throws me the same error.

**Comment by shivtrig** [comment]
@guillermo-navas-palencia When I removed the binning_fit_params and tried, I am able to pickle the binning_process object. But when I try to include the binning_fit_params, it throws me the above error. Do you know what might be the issue causing this?

**Comment by guillermo-navas-palencia** [comment]
Interesting. If binning_fit_params is the only difference, can you pickle this dict correctly? Otherwise, I do not see why it should cause an error.

**Comment by shivtrig** [comment]
Yes, I am able to pickle the binning_fit_params dictionary alone correctly. But when I declare it as a parameter in BinningProcess, I am unable to pickle the binning_process object. I feel that the problem is with binning_fit_params. When I remove it only, everything works fine.

**Comment by shivtrig** [comment]
Is there a workaround for this? Because I would be needing the binning_fit_params before fitting the binning process.

**Comment by guillermo-navas-palencia** [comment]
Well, I have tested the binning_fit_params on a Windows and Linux machine without issues. It is strange to me that a dict with pickleable types causes this issue. A workaround is fitting each optimal binning separately and building the binning process using the method ``fit_from_dict``, see: http://gnpalencia.org/optbinning/binning_process.html#optbinning.BinningProcess.fit_from_dict. Thus, you do not need to pass the binning_fit_params parameter.

**Comment by shivtrig** [comment]
@guillermo-navas-palencia It works finally! I removed the {"solver":"mip"} key-value pair from all the features and it works. Is this expected?

**Comment by guillermo-navas-palencia** [comment]
Hi @shivtrig. Glad it worked! I didn't try to pickle a binning process using MIP as a solver. The MIP option calls the C++ CBC solver included in Google OR-Tools, this might be the source of the problem. Good to know. 

On the other hand, the cp option is generally faster, and the only option for a continuous target.

**Comment by shivtrig** [comment]
@guillermo-navas-palencia Yeah, that might probably be the cause of this issue. Thank you! 
I tried using the MIP solver as mine was a binary target and the max_n_prebins was <=20. Maybe, you can have the option to pickle a binning process irrespective of the solvers in your future updates.

**Comment by guillermo-navas-palencia** [comment]
To clarify: the code implemented in OptBinning to pickle is the same for options mip and cp. The issue seems related to Google OR-Tools and it is beyond the scope of this discussion. The SwigPyObject is due to using swig to wrapper the C++ code with python.

However, using the default solver (cp) it should work. I just tested on a Windows machine and indeed I can reproduce the error by setting "solver": "mip". Therefore, I will add a warning in the documentation to not use solver mip if the binning process is going to be pickled.

Thank you for your feedback. I close this issue.

**Comment by shivtrig** [comment]
Hi @guillermo-navas-palencia,

Yeah, I know that. Anyways, the binning works fine now and I am able to pickle the binning process.  
Thank you for the quick replies and helping me out on this issue, much appreciated! Also, thank you for this library! It is really helpful and a good one.
